version: "3"

services:
  jekyll:
    build:
      context: ./dev/
    volumes:
      - ./:/srv/jekyll:Z
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
  lessc:
    image: finalgene/lessc
    volumes:
      - ./:/app
