version: "3"

services:
    jekyll:
        image: jekyll/jekyll:latest
        volumes:
            - ./:/srv/jekyll:Z
        ports:
          - "4000:4000"
        stdin_open: true
        tty: true
